
################################################################################
## Model VPC Script
## 
## Author: <add name>
## Date: <add date, for initial edits from template>
## Project: <add project identifier>
##
## Purpose:
##
## * This script reads in simulation runs of bbr model objects for the creation 
##   of VPCs. 
## * Example VPCs are shown at the bottom
## * There are _all sorts of ways_ you might modify this script; the code 
##   is provided as a starting point for implementing these changes as 
##   necessary based on the needs of the project or personal preferences.
##
################################################################################

#' Required packages
library(tidyverse)
library(mrggsave)
library(yspec)
library(here)
library(glue)
library(bbr)
library(vpc)
library(patchwork)
library(forcats)
source(here("scripts", "functions", "bbr-helpers.R"))

options(
  mrggsave.dir = here("results/figure"),
  mrgsolve.project = here("models/pk/simmod"),
  mrg.script = "scripts/vpc.R",
  mrggsave.dev = "png"
)

az_vpc_theme = new_vpc_theme(list(
  sim_pi_fill = "steelblue3", sim_pi_alpha = 0.5,
  sim_median_fill = "grey60", sim_median_alpha = 0.5
))

#' Load the data spec to generate labels
spec <- ys_load(here("data/derived/pk.yml"))
#spec <- ys_namespace(spec, "plot") # optionally uncomment to use alternate spec namespace
spec <- ys_extend(spec)
lab  <- ys_get_short_unit(spec, parens = TRUE)

#' # Requirements
#' 
#' In order to run this script, the user must have a model estimated in NONMEM 
#' as well as simulations from that model and the model estimation data set to 
#' support the vpc. Simulated data are generated using the 
#' `bbr::add_simulation()` function. Please see `model-management.Rmd` for the 
#' details of that simulation, including replicate number and handling of the 
#' data set for simulation. 
#' 
#' # Data
#' 
#' We'll read in both the observed data set as well as the simulated data that 
#' should already exist in the model run directory. Both will be read in using
#' `bbr` functions. 
#' 
#' We have some observations that are BQL that need to be dealt with. The limit 
#' of quantitation (LOQ) for this data is 10 ng/mL.  
#' 
#' We use a complete data approach, where we simulate the complete 
#' design (all intended samples) and then apply any BLQ rules accordingly 
#' (e.g., drop values less than the LOQ). Specifically, any code involving
#' 
#' filter(<simulated data>, DV <= 10) 
#' 
#' indicates that we are censoring the simulated data at the LOQ. Any code 
#' involving
#' 
#' filter(<observed data>, BLQ==0) 
#' 
#' indicates that we are removing BLQ observation records from the observed
#' data set.
#'  

runno <- 106
options(mrggsave.dir = here(glue("results/figure/{runno}")))
fs::dir_create(getOption("mrggsave.dir"))

#' Read in the complete data set
data <- nm_join(here(glue("models/pk/{runno}")), .superset = TRUE)

#' The estimation bbr model
mod <- read_model(here(glue("models/pk/{runno}")))
mod

#' Check that the attached simulation has been run
check_for_simulation_output(mod)

#' Read in the simulated data generated by the `bbr::add_simulation()` function
#' See `model-management.Rmd` for details for that simulation
sims <- nm_join_sim(mod)
head(sims)

#' The simulated data is a copy of the model estimation data set, with 
#' three new columns added: `DV` (the simulated data), `PRED` population 
#' predicted value for each row, and `nn`, the simulation replicate number.

range(sims$nn)
nrow(sims)/nrow(data)

#' Drop records that were commented from the model estimation run, saving 
#' records where DV is BLQ; we'll deal with those later when we censor the 
#' simulated data
#' 
#' There weren't any commented records in this data set; but you might have them
#' in your data set, hence the code.
data <- filter(data, is.na(C))
count(data, BLQ)

#' Groom observed and simulated data sets
#' - DVN: dose-normalized observed or simulated data
#' - CP, RF, DOSE are renamed as a simple way to generate a better facet label; 
#'   different projects could have different needs and handled differently
data <- ys_factors(data, spec, RF, CP)
data <- mutate(data, Hepatic = CP, Renal = RF, DVN = DV/DOSE)

sims <- ys_factors(sims, spec, RF, CP)
sims <- mutate(sims, Hepatic = CP, Renal = RF, DVN = DV/DOSE)

#' Set a factor for dose amount
udose <- sort(unique(data$DOSE))
data <- mutate(data, Dose = factor(DOSE, udose, paste("Dose:", udose, "mg")))
sims <- mutate(sims, Dose = factor(DOSE, udose, paste("Dose:", udose, "mg")))


#' Filter both the observed and simulated data
#' For the observed data, we only want actual observations that weren't BLQ
#' For the simulated data, we take simulated observations that were above LQ

#' # No impairment, SAD and MAD
fsad_mad <- filter(data, STUDYN <= 2)
fsims    <- filter(sims, STUDYN <= 2)

#' Filter both the observed and simulated data
fsad_mad <- filter(fsad_mad, EVID==0, BLQ == 0)
fsims    <- filter(fsims,    EVID==0, DV >= 10)

#' # Create the plot
#' 
#' Pass observed and simulated data into vpc function
p1 <- vpc(
  obs = fsad_mad,
  sim = fsims,
  stratify = "STUDY",
  obs_cols = list(dv = "DVN"),
  sim_cols = list(dv = "DVN", sim = "nn"), 
  log_y = TRUE,
  pi = c(0.05, 0.95),
  ci = c(0.025, 0.975), 
  facet = "columns",
  show = list(obs_dv = TRUE), 
  vpc_theme = az_vpc_theme
) 

p1 <- p1 + labs(x = lab$TIME, y = lab$DVNORM) + theme_bw(); p1

mrggsave_last(stem = "{runno}-pk-vpc-dose-norm", height = 7.5)

#' # Stratify on RF, renal study only
rf_data <- filter(data, STUDYN==3)
rf_sims <- filter(sims, STUDYN==3)

#' Filter both the observed and simulated data
f_rf_data <- filter(rf_data, EVID==0, BLQ == 0)
f_rf_sims <- filter(rf_sims, EVID==0, DV >= 10)

p2 <- vpc(
  obs = f_rf_data,
  sim = f_rf_sims,
  stratify = "Renal",
  obs_cols = list(dv = "DVN"),
  sim_cols = list(dv = "DVN", sim = "nn"), 
  log_y = TRUE,
  pi = c(0.05, 0.95),
  ci = c(0.025, 0.975), 
  show = list(obs_dv = TRUE), 
  vpc_theme = az_vpc_theme
) 

p2 <- p2 + labs(x = lab$TIME, y = lab$DVNORM) + theme_bw(); p2

mrggsave_last(stem = "{runno}-pk-vpc-dose-norm-rf", height = 6.5)

#' # Stratify on CP, hepatic study only
cp_data <- filter(data, STUDYN==4)
cp_sims <- filter(sims, STUDYN==4)

#' Filter both the observed and simulated data
f_cp_data <- filter(cp_data, EVID==0, BLQ == 0)
f_cp_sims <- filter(cp_sims, EVID==0, DV >= 10)

p3 <- vpc(
  obs = f_cp_data,
  sim = f_cp_sims,
  stratify = "Hepatic",
  obs_cols = list(dv = "DVN"),
  sim_cols = list(dv = "DVN", sim = "nn"), 
  log_y = TRUE,
  pi = c(0.05, 0.95),
  ci = c(0.025, 0.975), 
  labeller = label_value,
  show = list(obs_dv = TRUE), 
  vpc_theme = az_vpc_theme
) 

p3 <- p3 + labs(x = lab$TIME, y = lab$DVNORM) + theme_bw(); p3

mrggsave_last(stem = "{runno}-pk-vpc-dose-norm-cp", height = 6.5)


#' VPC for BLQ data. 
p4 <- vpc_cens(
  sim = sims, 
  obs = data, 
  stratify = "Dose",
  lloq = 10,
  obs_cols = list(dv = "DV"),
  sim_cols = list(dv = "DV", sim = "nn"), 
  vpc_theme = az_vpc_theme, 
  labeller = label_value
) + theme_bw()

p4 <- p4 + labs(x = lab$TIME); p4

mrggsave_last(stem = "{runno}-pk-vpc-blq", height = 7, width = 6)


#' # Concentration time on top, BLQ on bottom
#' 
#' - Stratify by DOSE
#' - I'm going to exclude some of the higher doses due to space limitations; 
#'   this can be customized according to the needs of the current problem
#' 
all_data <- filter(data, EVID==0, DOSE <= 50)
all_sims <- filter(sims, EVID==0, DOSE <= 50)

#' Concentration-time VPC
p5 <- vpc(
  obs = all_data %>% filter(BLQ==0),
  sim = all_sims %>% filter(DV >= 10),
  stratify = "Dose",
  obs_cols = list(dv = "DV", idv = "TAD"),
  sim_cols = list(dv = "DV", idv = "TAD", sim = "nn"), 
  log_y = TRUE,
  pred_corr = TRUE,
  pi = c(0.05, 0.95),
  ci = c(0.025, 0.975), 
  show = list(obs_dv = TRUE), 
  vpc_theme = az_vpc_theme, 
  labeller = label_value,
  facet = "rows", 
  xlab = lab$TAD,
  ylab = "Concentration (ng/mL)"
) + theme_bw()

#' VPC for BLQ data
p6 <- vpc_cens(
  obs = all_data,
  sim = all_sims,
  stratify = "Dose",
  lloq = 10,
  obs_cols = list(dv = "DV", idv = "TAD"),
  sim_cols = list(dv = "DV", idv = "TAD", sim = "nn"), 
  vpc_theme = az_vpc_theme, 
  labeller = label_value,
  facet = "rows", 
  xlab = lab$TAD, 
  ylab = "Pr <LOQ"
) + theme_bw() 

#' Combine into one plot
p6 <- p6 + theme(
  strip.background = element_blank(), 
  strip.text.x = element_blank()
) 

p7 <- p5 / p6 + plot_layout(axis_titles = "collect", heights = c(3,1)); p7

mrggsave(p7, stem = "{runno}-pk-vpc-conc-blq", height = 5, width = 8)
